### ISSUE TITLE
moveTo not working on slime and magma cube

### ISSUE THREAD

**Issue by IronGiu** [gmitch215/MobChip#118]
### Bug Type

Other Unexpected Behavior

### MobChip Version

1.9.5

### Server Version

Paper 1.20.4

### Description

I also tested it in the old Paper versions, like 1.20, 1.20.2 but nothing to do, the moveTo works for Villagers, Wolfs, Sheep etc, but not for Slime and Magma Cube

### Expected Behavior

N/A

### Actual Behavior

N/A

### Additional Information

test code used:

EntityBrain brain = BukkitBrain.getBrain(m);
EntityController controller = brain.getController();
Location target = player.getLocation();
controller.moveTo(target, 1);
controller.lookAt(target);

**Comment by GamerCoder215** [comment]
What’s unique about Slimes is the fact that they aren’t technically Creatures, whereas all the other ones are. I’ll have to see if they functionally have differences since they also specifically jump to get around.

**Comment by IronGiu** [comment]
i can not even move the dragon... i do something wrong? i tried with the above command, and event with:

DragonBrain brain = BukkitBrain.getBrain((EnderDragon) m);
EntityController controller = brain.getController();
Location targetai = player.getLocation();
controller.moveTo(targetai, 1);
controller.lookAt(targetai);

**Comment by gmitch215** [comment]
- Slimes (and inherently Magma Cubes) have their internal move controllers do nothing.
- The Ender Dragon is technically multiple entities at once, so It can't be controlled the normal way.

The best alternative is to use [setDeltaMovement](https://mobchip.gmitch215.xyz/me/gamercoder215/mobchip/ai/controller/EntityController.html#setDeltaMovement(org.bukkit.util.Vector)) which is like Bukkit's `setVelocity`, or use the [naturalMoveTo](https://mobchip.gmitch215.xyz/me/gamercoder215/mobchip/ai/controller/EntityController.html#naturalMoveTo(double,double,double,me.gamercoder215.mobchip.ai.controller.NaturalMoveType)) function.
