### ISSUE TITLE
How to make ender dragon move to certain cords?

### ISSUE THREAD

**Issue by ItsHarshXD** [gmitch215/MobChip#124]
### Feature Type

Other

### Description of Feature

Hi, I just want to know that by using this API, can i make a dragon which will fly to a certain cords in overworld?

**Comment by gmitch215** [comment]
EnderDragon internally uses `naturalMoveTo` with (`NaturalMoveType.SELF`) to get around, so you can try that method. Let me know if it doesn't work.

One thing to note is that `naturalMoveTo` is relative, so to get to specific coords, you'll need to do something like this:

```java
Location coords = ...
DragonBrain brain = (DraginBrain) BukkitBrain.getBrain(dragon);

brain.getController().naturalMoveTo(coords.getX() - dragon.getLocation().getX(), coords.getY() - dragon.getLocation().getY(), coords.getZ() - dragon.getLocation().getZ());
```

**Comment by ItsHarshXD** [comment]
> EnderDragon internally uses `naturalMoveTo` with (`NaturalMoveType.SELF`) to get around, so you can try that method. Let me know if it doesn't work.
> 
> One thing to note is that `naturalMoveTo` is relative, so to get to specific coords, you'll need to do something like this:
> 
> ```java
> Location coords = ...
> DragonBrain brain = (DraginBrain) BukkitBrain.getBrain(dragon);
> 
> brain.getController().naturalMoveTo(coords.getX() - dragon.getLocation().getX(), coords.getY() - dragon.getLocation().getY(), coords.getZ() - dragon.getLocation().getZ());
> ```

I'm using MythicMob API to get entity (it is ender dragon), so is this the way to use that entity in DragonBrain variable?

`            ActiveMob dragon = mob.spawn(BukkitAdapter.adapt(spawnLocation), 1);
            Entity entity = dragon.getEntity().getBukkitEntity();
            DragonBrain brain = (DragonBrain) BukkitBrain.getBrain((Mob) dragon);

            brain.getController().naturalMoveTo(endLocation.getX() - dragon.getLocation().getX(), endLocation.getY() - dragon.getLocation().getY(), endLocation.getZ() - dragon.getLocation().getZ(), NaturalMoveType.SELF);
            addPassengersWithDelay(entity);`

**Comment by gmitch215** [comment]
`dragon` is the bukkit entity, instead of casting the ActiveMob class use the `entity` variable instead. Otherwise, everything should work if your variables are correct.

**Comment by ItsHarshXD** [comment]
> `dragon` is the bukkit entity, instead of casting the ActiveMob class use the `entity` variable instead. Otherwise, everything should work if your variables are correct.

I tried, but won't work, can you please send me the entity variable for ender dragon please?

**Comment by gmitch215** [comment]
> > `dragon` is the bukkit entity, instead of casting the ActiveMob class use the `entity` variable instead. Otherwise, everything should work if your variables are correct.
> 
> I tried, but won't work, can you please send me the entity variable for ender dragon please?

I'm talking about the `entity` variable you declared earlier. This should be your code:

```java
  // MythicMob API code to get entity and spawn it
  ActiveMob dragon = mob.spawn(BukkitAdapter.adapt(spawnLocation), 1);
  Entity entity = dragon.getEntity().getBukkitEntity();
  DragonBrain brain = (DragonBrain) BukkitBrain.getBrain((EnderDragon) entity);

  brain.getController().naturalMoveTo(endLocation.getX() - dragon.getLocation().getX(), endLocation.getY() - 
  dragon.getLocation().getY(), endLocation.getZ() - dragon.getLocation().getZ(), NaturalMoveType.SELF);
```

**Comment by gmitch215** [comment]
Going to close this since there has been no response.

**Comment by gmitch215** [comment]
It should. If not, you can try `moveTo` instead, which just takes the location as a parameter.
