### ISSUE TITLE
Option to install MobChip as a plugin

### ISSUE THREAD

**Issue by PikaMug** [gmitch215/MobChip#125]
### Feature Type

Compatibility

### Description of Feature

Would you consider adding a JavaPlugin class, plugin.yml, etc. so that the library may alternatively be installed as a plugin? This would be useful for developers whom don't want—or frankly, don't know how—to shade into an uber jar, and better position the project for a Resource page on SpigotMC under [Libraries / APIs](https://www.spigotmc.org/resources/categories/libraries-apis.26/). I realize you might be focusing on other projects soon, but I feel a polished download page might attract the right eyes to PR this into 1.21 and beyond.

**Comment by gmitch215** [comment]
While I'd be willing to work on this project for a bit longer, I don't think this is a good idea. There are multiple examples, such as:

- Version incompatibility between plugins (despite the lack of updates, this is still a possibility)
- Failure example for shading projects
- Lack of real-world application as a shaded library

I also don't like (soft)-depending on other plugins in general, as it causes more work by the users. MobChip is supposed to be a library for `complex` plugins by developers who know how to implement proper OOP, Java, and build system standards, and sugarcoating that standard will not be beneficial for any developer in the future, even if they have a preference against it.

If you're worried about the setup, look into [shadowJar](https://plugins.gradle.org/plugin/io.github.goooler.shadow) for Gradle or the [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/usage.html) for Maven.

**Comment by PikaMug** [comment]
I feel like there's an argument to be made for each of those bullets, but I respect sticking to your philosophy. That said, please still consider releasing MobChip as a formal Resource, and perhaps on other platforms, even if it runs the risk of "thIs plug1n doesNt w0rk." Limiting your great work to the forum thread doesn't do it justice :)
