### ISSUE TITLE
EnderDragon doesn't move

### ISSUE THREAD

**Issue by ItsHarshXD** [gmitch215/MobChip#131]
### Bug Type

Other Unexpected Behavior

### MobChip Version

1.10.1

### Server Version

1.20.4

### Description

I'm using this code to make the dragon fly towards the location but it teleports me there directly.

Code:

```java    public void spawnDragonPassengers(Player player) {
        Location location = player.getLocation();
        EnderDragon dragon = (EnderDragon) Bukkit.getWorld("world").spawnEntity(location, EntityType.ENDER_DRAGON);

        Location endLocation = new Location (Bukkit.getWorld("world"), 500, 100, 500);

        DragonBrain brain = (DragonBrain) BukkitBrain.getBrain(dragon);
        brain.getController().naturalMoveTo(endLocation.getX() - dragon.getLocation().getX(), endLocation.getY() -
                dragon.getLocation().getY(), endLocation.getZ() - dragon.getLocation().getZ(), NaturalMoveType.SELF);

        dragon.addPassenger(player);
        player.sendMessage("Ender Dragon summoned and moving to target location!");
    }
```

### Expected Behavior

It should actually move towards specified location.

### Actual Behavior

The dragon spawned suddenly teleporting to 500 100 500 (cords set by me).

**Comment by gmitch215** [comment]
> ### Bug Type
> 
> Other Unexpected Behavior
> ### MobChip Version
> 
> 1.10.1
> ### Server Version
> 
> 1.20.4
> ### Description
> 
> I'm using this code to make the dragon fly towards the location but it teleports me there directly.
> 
> Code:
> 
> ```java
>         Location location = player.getLocation();
>         EnderDragon dragon = (EnderDragon) Bukkit.getWorld("world").spawnEntity(location, EntityType.ENDER_DRAGON);
> 
>         Location endLocation = new Location (Bukkit.getWorld("world"), 500, 100, 500);
> 
>         DragonBrain brain = (DragonBrain) BukkitBrain.getBrain(dragon);
>         brain.getController().naturalMoveTo(endLocation.getX() - dragon.getLocation().getX(), endLocation.getY() -
>                 dragon.getLocation().getY(), endLocation.getZ() - dragon.getLocation().getZ(), NaturalMoveType.SELF);
> 
>         dragon.addPassenger(player);
>         player.sendMessage("Ender Dragon summoned and moving to target location!");
>     }
> ```
> 
> ### Expected Behavior
> 
> It should actually move towards specified location.
> ### Actual Behavior
> 
> The dragon spawned suddenly teleporting to 500 100 500 (cords set by me).
> ### Additional Information
> 
> _No response_

If your coordinates are too far away, it will teleport. I can't control that since it's what Minecraft does.

You can try using the [Entity Navigation](https://github.com/gmitch215/MobChip/wiki/Entity-Controllers-%7C-Navigation) API, but this uses `moveTo` which may not work on a dragon. Alternatively, you can use multiple points using `naturalMoveTo`.

**Comment by ItsHarshXD** [comment]
> If your coordinates are too far away, it will teleport. I can't control that since it's what Minecraft does.
> 
> You can try using the [Entity Navigation](https://github.com/gmitch215/MobChip/wiki/Entity-Controllers-%7C-Navigation) API, but this uses `moveTo` which may not work on a dragon. Alternatively, you can use multiple points using `naturalMoveTo`.

Still it doesn't travel when im close to 500, 100, 500

**Comment by gmitch215** [comment]
Can you specify how close you are to the coordinates?
